name: "build-test"
on:
  pull_request:

jobs:  
  test-chuck: # make sure the action works on a clean machine without building    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - id: prComment
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment_type: 'chuck'
      - name: Print comment URL
        run: echo "Comment URL- ${{ steps.prComment.outputs.comment-url }}"