name: GitHub Actions Demo
on:
  pull_request:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: python lyrics.py
      - run: echo "Printing lyrics!"
  Add-comment: 
    runs-on: ubuntu-latest
    steps:
      - name: Add funny comment
        uses: Marta83/funny-comment-action@v2.1
        id: FunnyComment
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
          comment_type: 'chuck'
      - name: Print comment URL
        run: echo "Comment URL- ${{ steps.prComment.outputs.comment-url }}"
  Run-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: thursday_actions
          environment-file: environment.yml
      - name: Execute tests
        run: python -u -m pytest --headless tests 

      